# .github/workflows/cicd.yml
name: Weekly Automation Test

on:
  schedule:
    - cron: "0 1 * * 1"  # 每週一早上 9 點 (UTC +8)
  workflow_dispatch:
    inputs:
      environment:
        description: '選擇環境'
        required: true
        default: 'qat'
        type: choice
        options:
        - qat
        - uat

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || github.event.inputs.environment }}
      
    steps:
      - name: Clean Workspace
        run: rm -rf *

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        run: |
          docker build -t swag-automation-qa .
          docker run -d --name automation-test-container \
            -e ENVIRONMENT=${{ env.ENVIRONMENT }} \
            swag-automation-qa

      - name: Execute Tests in Docker
        run: |
          docker exec automation-test-container /bin/bash -c "
          source /venv/bin/activate && \
          mkdir -p /results && \
          cd /swag_Automation_QA && \
          robot -V data.yaml -V country.yaml -V ${ENVIRONMENT}_domain.yaml \
          -i login \
          --outputdir /results \
          TestCase"

      - name: Collect Test Results
        run: docker cp automation-test-container:/results ./results

      - name: Stop and Remove Docker Container
        run: |
          docker stop automation-test-container
          docker rm automation-test-container

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
