name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"  # 每週一上午 10 點觸發
  workflow_dispatch:       # 手動觸發

jobs:
  run_tests:
    runs-on: macos-latest  # 使用 macOS 環境
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          brew install --cask google-chrome

      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip setuptools
          pip install -r swag_Automation_QA/requirements.txt

      - name: Copy Required Files
        run: |
          cp swag_Automation_QA/data.yaml /app/data.yaml
          cp swag_Automation_QA/qat_domain.yaml /app/qat_domain.yaml

      - name: Run Tests
        run: |
          source venv/bin/activate
          robot -V /app/data.yaml -V /app/qat_domain.yaml -i login swag_Automation_QA/TestCase

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            swag_Automation_QA/report.html
            swag_Automation_QA/reports/
