name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true
      
      - name: Install Chrome
        run: |
          brew install --cask google-chrome
          echo "Chrome version: $(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)"
      
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          brew install --cask chromedriver
          chromedriver --version
      
      - name: Setup Chrome
        run: |
          sudo chmod -R 755 /opt/homebrew/bin/chromedriver
          chromedriver --port=4444 &
          sleep 5
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install -r swag_Automation_QA/requirements.txt
      
      # 新增：檢查目錄結構和檔案
      - name: Check Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -R
          
          echo "\nVerifying YAML files:"
          ls -l swag_Automation_QA/*.yaml
          
          echo "\nVerifying Robot Resource files:"
          ls -l swag_Automation_QA/keyword/swag/

      # 新增：創建必要的目錄結構
      - name: Create Required Directories
        run: |
          mkdir -p swag_Automation_QA/keyword/swag/
          
      # 新增：複製關鍵字文件
      - name: Copy Robot Resource Files
        run: |
          cp swag_Automation_QA/keyword/Swag.sources.robot swag_Automation_QA/keyword/swag/
      
      - name: Run Tests
        env:
          PYTHONPATH: ${GITHUB_WORKSPACE}/swag_Automation_QA/keyword
          DISPLAY: :99
        run: |
          sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          
          robot \
            --variable BROWSER:chrome \
            --outputdir results \
            --pythonpath swag_Automation_QA/keyword \
            --pythonpath swag_Automation_QA/keyword/swag \
            -V swag_Automation_QA/data.yaml \
            -V swag_Automation_QA/qat_domain.yaml \
            -V swag_Automation_QA/country.yaml \
            -i login swag_Automation_QA/TestCase
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            swag_Automation_QA/reports/