name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 設置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # 建立並運行 Docker 容器
      - name: Build and Run Docker
        run: |
          docker build -t swag-test -f swag_Automation_QA/Dockerfile .
          docker run \
            -v ${PWD}/swag_Automation_QA:/app/swag_Automation_QA \
            -v ${PWD}/results:/app/results \
            swag-test \
            robot \
              --variable BROWSER:chrome \
              --outputdir /app/results \
              --pythonpath /app/swag_Automation_QA/keyword/swag \
              --variablefile /app/swag_Automation_QA/data.yaml \
              --variablefile /app/swag_Automation_QA/qat_domain.yaml \
              --variablefile /app/swag_Automation_QA/country.yaml \
              -i login /app/swag_Automation_QA/TestCase
      
      # 上傳測試結果
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            swag_Automation_QA/reports/