name: SWAG 自動化測試

on:
  schedule:
    - cron: '0 9 * * 1'
  
  pull_request:
    types: [opened, synchronize, reopened]
    labels:
      - e2e
  
  workflow_dispatch:
    inputs:
      environment:
        description: '選擇測試環境'
        required: true
        default: 'qat'
        type: choice
        options:
        - qat
        - uat
      test_type:
        description: '選擇測試類型'
        required: true
        default: 'bvt'
        type: choice
        options:
        - bvt
        - login
        - register
        - video
        - myprofile

jobs:
  test:
    runs-on: [self-hosted, macos]
    
    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      TEST_TYPE: ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request') && 'bvt' || inputs.test_type }}
      PYTHONPATH: ${{ github.workspace }}/swag_Automation_QA/robotframework/robot_lib
      OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
    
    steps:
      - name: 清理工作區
        run: |
          rm -rf *
          rm -rf .git*
          
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Python 環境
        run: |
          # 使用 Rosetta 2 創建 x86_64 Python 環境
          arch -x86_64 python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip

      - name: 安裝依賴套件
        run: |
          source venv/bin/activate
          # 使用 Rosetta 2 安裝套件
          arch -x86_64 pip install \
            robotframework==7.0.1 \
            robotframework-seleniumlibrary==6.3.0 \
            robotframework-selenium2library==3.0.0 \
            selenium==4.23.1 \
            pyotp==2.9.0 \
            robotframework-requests==0.9.7 \
            robotframework-jsonlibrary==0.5 \
            requests==2.32.3 \
            PyYAML==6.0.2 \
            python-dotenv==1.0.1 \
            cryptography==43.0.0 \
            pyOpenSSL==24.2.1 \
            Faker==27.0.0 \
            webdriver-manager==4.0.2 \
            robotframework-jsonvalidator==2.0.0 \
            robotframework-debuglibrary==2.5.0 \
            charset-normalizer

      - name: 執行測試
        id: test
        continue-on-error: true
        run: |
          source venv/bin/activate
          cd swag_Automation_QA
          
          # 設定環境變數
          export PYTHONPATH=$PWD/robotframework/robot_lib:$PYTHONPATH
          export DISPLAY=:0
          
          # 確保目錄存在
          mkdir -p results
          
          # 執行測試
          robot \
            -v BROWSER:chrome \
            -v SELENIUM_TIMEOUT:60 \
            -v SELENIUM_IMPLICIT_WAIT:30 \
            -v BROWSER_OPTIONS:"add_argument('--no-sandbox');add_argument('--start-maximized');add_argument('--disable-dev-shm-usage');add_argument('--disable-gpu');add_argument('--window-size=1920,1080');add_argument('--disable-notifications');add_argument('--disable-popup-blocking');add_argument('--remote-debugging-port=9222');add_argument('--disable-features=TranslateUI')" \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i ${TEST_TYPE} \
            --outputdir results \
            TestCase

      - name: 上傳測試結果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.TEST_TYPE }}
          path: |
            swag_Automation_QA/results/
            swag_Automation_QA/reports/
          if-no-files-found: warn
          
      - name: 清理環境
        if: always()
        run: |
          pkill -f "Google Chrome" || true
          pkill -f "chromedriver" || true
          rm -rf venv
          rm -rf ~/Library/Application\ Support/Google/Chrome/Default/*