name: SWAG 自動化測試

on:
  schedule:
    - cron: '0 9 * * 1'
  
  pull_request:
    types: [opened, synchronize, reopened]
    labels:
      - e2e
  
  workflow_dispatch:
    inputs:
      environment:
        description: '選擇測試環境'
        required: true
        default: 'qat'
        type: choice
        options:
        - qat
        - uat
      test_type:
        description: '選擇測試類型'
        required: true
        default: 'bvt'
        type: choice
        options:
        - bvt
        - login
        - register
        - video
        - myprofile

jobs:
  test:
    runs-on: [self-hosted, macos]
    
    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      TEST_TYPE: ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request') && 'bvt' || inputs.test_type }}
      PYTHONPATH: ${{ github.workspace }}/swag_Automation_QA/robotframework/robot_lib
      ROBOT_ARGS: --outputdir results
    
    steps:
      - name: 清理環境
        run: |
          rm -rf *
          rm -rf .git*
          # 清理 Python 緩存
          find . -type d -name "__pycache__" -exec rm -rf {} +
          
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Python 環境
        run: |
          # 確保使用系統 Python
          which python3
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          
      - name: 安裝 Python 套件
        run: |
          # 強制重新安裝套件以確保架構正確
          ARCHFLAGS="-arch arm64" pip install --force-reinstall \
            robotframework==7.0.1 \
            robotframework-seleniumlibrary==6.3.0 \
            robotframework-selenium2library==3.0.0 \
            selenium==4.23.1 \
            pyotp==2.9.0 \
            robotframework-requests==0.9.7 \
            robotframework-jsonlibrary==0.5 \
            requests==2.32.3 \
            PyYAML==6.0.2 \
            python-dotenv==1.0.1 \
            cryptography==43.0.0 \
            pyOpenSSL==24.2.1 \
            Faker==27.0.0 \
            webdriver-manager==4.0.2 \
            robotframework-jsonvalidator==2.0.0 \
            robotframework-debuglibrary==2.5.0

      - name: 設定 Chrome
        run: |
          # 確保 Chrome 是最新版本
          brew upgrade --cask google-chrome || brew install --cask google-chrome
          # 安裝對應版本的 ChromeDriver
          brew upgrade --cask chromedriver || brew install --cask chromedriver
          
          # 設定權限
          sudo xattr -rd com.apple.quarantine /Applications/Google\ Chrome.app || true
          sudo xattr -rd com.apple.quarantine $(which chromedriver) || true
          
          # 檢查版本
          chrome_version=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | cut -d " " -f 3)
          chromedriver_version=$(chromedriver --version | cut -d " " -f 2)
          echo "Chrome version: $chrome_version"
          echo "ChromeDriver version: $chromedriver_version"

      - name: 執行測試
        id: test
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          source ../venv/bin/activate
          
          # 設定環境變數
          export PYTHONPATH=$PWD/robotframework/robot_lib:$PYTHONPATH
          export ROBOT_SUITENAMES="TestCase"
          
          # 建立結果目錄
          mkdir -p results
          
          # 執行測試
          robot \
            -v BROWSER:chrome \
            -v SELENIUM_TIMEOUT:60 \
            -v SELENIUM_IMPLICIT_WAIT:30 \
            -v BROWSER_OPTIONS:"add_argument('--no-sandbox');add_argument('--start-maximized');add_argument('--disable-dev-shm-usage');add_argument('--disable-gpu');add_argument('--window-size=1920,1080');add_argument('--disable-notifications');add_argument('--enable-automation');add_argument('--remote-debugging-port=9222')" \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i ${TEST_TYPE} \
            --outputdir results \
            TestCase

      - name: 上傳測試結果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.TEST_TYPE }}
          path: |
            swag_Automation_QA/results/
            swag_Automation_QA/reports/
          if-no-files-found: warn
          
      - name: 清理環境
        if: always()
        run: |
          pkill -f "Google Chrome" || true
          pkill -f "chromedriver" || true
          rm -rf venv