name: SWAG 自動化測試

on:
  schedule:
    - cron: '0 9 * * 1'  # 每週一早上 9:00
  
  pull_request:
    types: [opened, synchronize, reopened]
    labels:
      - e2e
  
  workflow_dispatch:
    inputs:
      environment:
        description: '選擇測試環境'
        required: true
        default: 'qat'
        type: choice
        options:
        - qat
        - uat
      test_type:
        description: '選擇測試類型'
        required: true
        default: 'bvt'
        type: choice
        options:
        - bvt
        - login
        - register
        - video
        - myprofile

jobs:
  test:
    runs-on: macos-latest
    
    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      TEST_TYPE: ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request') && 'bvt' || inputs.test_type }}
    
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 建立 Requirements 文件
        run: |
          cat << EOF > requirements.txt
          robotframework==7.0.1
          robotframework-datetime-tz==1.0.6
          robotframework-debuglibrary==2.5.0
          robotframework-faker==5.0.0
          robotframework-jsonlibrary==0.5
          robotframework-jsonvalidator==2.0.0
          robotframework-pythonlibcore==4.4.1
          robotframework-randomlibrary==0.0.2
          robotframework-requests==0.9.7
          robotframework-selenium2library==3.0.0
          robotframework-seleniumlibrary==6.3.0
          robotframework-yamllibrary==0.2.8
          selenium==4.23.1
          webdriver-manager==4.0.2
          Faker==27.0.0
          requests==2.32.3
          PyYAML==6.0.2
          python-dotenv==1.0.1
          cryptography==43.0.0
          pyOpenSSL==24.2.1
          EOF

      - name: 設定 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: 安裝 Chrome
        run: |
          brew update
          brew install --cask google-chrome
          brew install --cask chromedriver
          
      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 執行自動化測試
        id: initial_test
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          robot \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i ${TEST_TYPE} \
            TestCase

      - name: 重新執行失敗的測試
        if: steps.initial_test.outcome == 'failure'
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          if [ -f "output.xml" ]; then
            robot \
              --rerunfailed output.xml \
              -V data.yaml \
              -V country.yaml \
              -V ${ENVIRONMENT}_domain.yaml \
              -i ${TEST_TYPE} \
              TestCase
          else
            echo "找不到 output.xml 檔案"
            exit 0
          fi

      - name: 合併測試結果
        if: steps.initial_test.outcome == 'failure'
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          if [ -f "output.xml" ] && [ -f "output.xml" ]; then
            rebot \
              --output merged-output.xml \
              --merge \
              output.xml \
              output.xml
          fi

      - name: 上傳測試結果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.TEST_TYPE }}
          path: |
            swag_Automation_QA/*.xml
            swag_Automation_QA/log.html
            swag_Automation_QA/report.html
          if-no-files-found: warn