name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      # 新增詳細檢查目錄結構
      - name: Check Directory Structure
        run: |
          echo "顯示當前工作目錄:"
          pwd
          echo "\n顯示 swag_Automation_QA 目錄結構:"
          ls -R swag_Automation_QA/
          echo "\n尋找所有 .yaml 文件:"
          find . -name "*.yaml"
          echo "\n尋找所有 .robot 文件:"
          find . -name "*.robot"
          
      # 新增建立必要目錄
      - name: Create Required Structure
        run: |
          mkdir -p swag_Automation_QA/keyword/swag/
          
      # 新增建立基本 Swag.sources.robot 檔案
      - name: Create Basic Robot Resource File
        run: |
          cat << 'EOF' > swag_Automation_QA/keyword/swag/Swag.sources.robot
          *** Settings ***
          Library    SeleniumLibrary

          *** Keywords ***
          開啟Chrome瀏覽器
              ${chrome_options}=    Evaluate    selenium.webdriver.ChromeOptions()
              Call Method    ${chrome_options}    add_argument    --start-maximized
              Call Method    ${chrome_options}    add_argument    --no-sandbox
              Call Method    ${chrome_options}    add_argument    --disable-dev-shm-usage
              Create Webdriver    Chrome    chrome_options=${chrome_options}
              Set Window Size    1920    1080

          關閉所有瀏覽器
              Close All Browsers
          EOF

      - name: Install Chrome
        run: |
          brew install --cask google-chrome
          echo "Chrome version: $(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)"
      
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          brew install --cask chromedriver
          chromedriver --version
      
      - name: Setup Chrome
        run: |
          sudo chmod -R 755 /opt/homebrew/bin/chromedriver
          chromedriver --port=4444 &
          sleep 5
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium
          pip install -r swag_Automation_QA/requirements.txt
      
      - name: Run Tests
        env:
          DISPLAY: :99
        run: |
          sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 2
          
          robot \
            --variable BROWSER:chrome \
            --outputdir results \
            --pythonpath swag_Automation_QA/keyword/swag \
            --variablefile swag_Automation_QA/data.yaml \
            --variablefile swag_Automation_QA/qat_domain.yaml \
            --variablefile swag_Automation_QA/country.yaml \
            -i login swag_Automation_QA/TestCase
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            swag_Automation_QA/reports/