name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install Chrome
        run: |
          brew install --cask google-chrome
          
      - name: Install Chrome WebDriver
        run: |
          brew install chromedriver
          
      - name: Verify Directory Structure
        run: |
          pwd
          ls -la
          ls -R swag_Automation_QA/
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install -r swag_Automation_QA/requirements.txt
          
      - name: Check YAML Files
        run: |
          if [ -f "swag_Automation_QA/data.yaml" ]; then
            echo "data.yaml exists"
          else
            echo "data.yaml not found"
          fi
          if [ -f "swag_Automation_QA/qat_domain.yaml" ]; then
            echo "qat_domain.yaml exists"
          else
            echo "qat_domain.yaml not found"
          fi
      
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}/swag_Automation_QA/keyword
          robot \
            --variable BROWSER:headlesschrome \
            --outputdir results \
            -V swag_Automation_QA/data.yaml \
            -V swag_Automation_QA/qat_domain.yaml \
            -V swag_Automation_QA/country.yaml \
            -i login swag_Automation_QA/TestCase
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            swag_Automation_QA/reports/