name: SWAG 自動化測試

on:
  schedule:
    - cron: '0 9 * * 1'

  pull_request:
    types: [opened, synchronize, reopened]
    labels:
      - e2e

  workflow_dispatch:
    inputs:
      environment:
        description: '選擇測試環境'
        required: true
        default: 'qat'
        type: choice
        options:
          - qat
          - uat
      test_type:
        description: '選擇測試類型'
        required: true
        default: 'bvt'
        type: choice
        options:
          - bvt
          - login
          - register
          - video
          - myprofile
      custom_domain:
        description: '自定義測試網域 (例如: v3-211.app.swag.live)'
        required: false
        type: string
        default: 'swag.live'

jobs:
  test:
    runs-on: [self-hosted, macos]

    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      TEST_TYPE: ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request') && 'bvt' || inputs.test_type }}
      PYTHONPATH: ${{ github.workspace }}/swag_Automation_QA/robotframework/robot_lib

    steps:
      - name: 清理工作區
        run: |
          rm -rf swag_Automation_QA/*.xml
          rm -rf swag_Automation_QA/*.html

      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 更新網域設定
        if: inputs.custom_domain != ''
        run: |
          cd swag_Automation_QA
          # 備份原始檔案
          cp ${ENVIRONMENT}_domain.yaml ${ENVIRONMENT}_domain.yaml.bak
          
          # 使用 Python 更新 YAML 檔案
          python3 <<EOF
          import yaml
          
          # 讀取原始設定
          with open('${ENVIRONMENT}_domain.yaml', 'r', encoding='utf-8') as file:
              config = yaml.safe_load(file)
          
          # 更新網域
          custom_domain = '${{ inputs.custom_domain }}'
          config['SWAG_BASE_URL'] = f'https://{custom_domain}/?lang=zh-TW'
          
          # 寫回檔案
          with open('${ENVIRONMENT}_domain.yaml', 'w', encoding='utf-8') as file:
              yaml.dump(config, file, allow_unicode=True, default_flow_style=False)
              
          # 印出更新後的內容以供確認
          print("更新後的網域設定：")
          print(f"SWAG_BASE_URL: {config['SWAG_BASE_URL']}")
          EOF

      - name: 執行測試
        id: test
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          arch -arm64 robot \
            -v BROWSER:chrome \
            -v SELENIUM_TIMEOUT:60 \
            -v SELENIUM_IMPLICIT_WAIT:30 \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i ${TEST_TYPE} \
            TestCase

      - name: 分析測試結果
        id: analyze_results
        run: |
          python3 <<EOF
          import os
          from xml.etree import ElementTree as ET
          from datetime import datetime

          result_file = 'swag_Automation_QA/output.xml'
          pass_count = fail_count = 0

          try:
              if os.path.exists(result_file):
                  tree = ET.parse(result_file)
                  root = tree.getroot()
                  for suite in root.findall('.//suite'):
                      for test in suite.findall('.//test'):
                          status_elem = test.find('status')
                          if status_elem is not None:
                              status = status_elem.get('status', '').upper()
                              if status == 'PASS':
                                  pass_count += 1
                              elif status == 'FAIL':
                                  fail_count += 1

                  print(f"測試完成！\n通過測試數: {pass_count}\n失敗測試數: {fail_count}")
                  
                  # 輸出測試結果狀態供後續步驟使用
                  with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                      status_icon = '✅PASS' if fail_count == 0 else '❌FAIL'
                      current_time = datetime.now().strftime('%Y%m%d_%H%M%S')
                      env_file.write(f'TEST_STATUS={status_icon}\n')
                      env_file.write(f'CURRENT_TIME={current_time}\n')
                  
                  if fail_count > 0:
                      exit(1)
              else:
                  print(f"找不到測試結果檔案：{result_file}")
                  exit(1)
          except Exception as e:
              print(f"分析測試結果時發生錯誤：{str(e)}")
              exit(1)
          EOF

      - name: 打印測試結果
        if: success()
        run: echo "所有測試均通過！"

      - name: 打印失敗結果
        if: failure()
        run: echo "部分測試失敗，請檢查測試結果！"

      - name: 上傳測試結果
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEST_STATUS }}-test-results-${{ env.TEST_TYPE }}_${{ env.CURRENT_TIME }}
          path: |
            swag_Automation_QA/*.xml
            swag_Automation_QA/*.html
          if-no-files-found: warn