name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      # 檢出代碼
      - name: Checkout Code
        uses: actions/checkout@v4

      # 創建虛擬環境並升級 pip 和 setuptools
      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip setuptools

      # 安裝依賴
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r swag_Automation_QA/requirements.txt

      # 運行 Robot Framework 測試
      - name: Run Tests
        run: |
          source venv/bin/activate
          robot -V swag_Automation_QA/data.yaml -V swag_Automation_QA/country.yaml -V swag_Automation_QA/qat_domain.yaml -i login swag_Automation_QA/TestCase

      # 上傳測試報告到 GitHub Artifact
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            swag_Automation_QA/report.html
            swag_Automation_QA/reports/

      # 將測試報告推送到 GitHub Repository
      - name: Commit and Push Report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add swag_Automation_QA/report.html swag_Automation_QA/reports/
          git commit -m "Update test report [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
