name: Weekly Automation Test

on:
  schedule:
    - cron: "*/30 * * * *"  # 每半小時執行一次
  workflow_dispatch:
    inputs:
      environment:
        description: '選擇環境'
        required: true
        default: 'qat'
        type: choice
        options:
        - qat
        - uat

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      
    steps:
      - name: Clean Workspace
        run: rm -rf *
      
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-full python3-pip xvfb

      - name: Install Robot Framework
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install \
            robotframework \
            robotframework-seleniumlibrary \
            robotframework-requests \
            robotframework-jsonlibrary \
            selenium \
            requests \
            pyyaml
      
      - name: Setup Chrome and ChromeDriver
        run: |
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | cut -d " " -f 3)
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d "." -f 1)
          
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}"
          wget -q "https://chromedriver.storage.googleapis.com/$(cat LATEST_RELEASE_${CHROME_MAJOR_VERSION})/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          chromedriver --port=4444 &
          sleep 2

      - name: Start Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3
      
      - name: Create Required Directories
        run: |
          mkdir -p results
          mkdir -p rerun_results
      
      - name: Run Initial Tests
        id: initial_test
        continue-on-error: true
        env:
          DISPLAY: :99
        run: |
          source venv/bin/activate
          robot \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i login TestCase
      
      - name: Rerun Failed Tests
        if: steps.initial_test.outcome == 'failure'
        continue-on-error: true
        env:
          DISPLAY: :99
        run: |
          source venv/bin/activate
          robot \
            --rerunfailed results/output.xml \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i login TestCase

      - name: Merge Test Results
        if: steps.initial_test.outcome == 'failure'
        env:
          DISPLAY: :99
        run: |
          source venv/bin/activate
          rebot \
            --output results/output.xml \
            --merge \
            results/output.xml \
            rerun_results/output.xml
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            rerun_results/