name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # 建立並運行 Docker 容器
      - name: Build and Run Docker
        run: |
          # 顯示目錄結構
          echo "Current directory structure:"
          ls -R swag_Automation_QA/
          
          # 建立並運行容器
          docker build -t swag-test -f swag_Automation_QA/Dockerfile .
          docker run --shm-size=2g \
            -v ${PWD}/results:/app/results \
            swag-test
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            results/
            swag_Automation_QA/reports/