name: Weekly Automation Test

on:
  schedule:
    - cron: "0 10 * * 1"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -R swag_Automation_QA

      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip setuptools
          pip install -r swag_Automation_QA/requirements.txt

      - name: Install Browser Library
        run: |
          source venv/bin/activate
          pip install robotframework-browser
          rfbrowser init

      - name: Run Tests
        run: |
          source venv/bin/activate
          robot -V swag_Automation_QA/data.yaml -V swag_Automation_QA/country.yaml -V swag_Automation_QA/qat_domain.yaml -i login swag_Automation_QA/TestCase

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            swag_Automation_QA/report.html
            swag_Automation_QA/reports/

      - name: Commit and Push Report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add swag_Automation_QA/report.html swag_Automation_QA/reports/
          git commit -m "Update test report [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
