name: SWAG 自動化測試

on:
  schedule:
    - cron: '0 9 * * 1'

  pull_request:
    types: [opened, synchronize, reopened]
    labels:
      - e2e

  workflow_dispatch:
    inputs:
      environment:
        description: '選擇測試環境'
        required: true
        default: 'qat'
        type: choice
        options:
          - qat
          - uat
      test_type:
        description: '選擇測試類型'
        required: true
        default: 'bvt'
        type: choice
        options:
          - bvt
          - login
          - register
          - video
          - myprofile

jobs:
  test:
    runs-on: [self-hosted, macos]

    env:
      ENVIRONMENT: ${{ github.event_name == 'schedule' && 'uat' || inputs.environment }}
      TEST_TYPE: ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request') && 'bvt' || inputs.test_type }}
      PYTHONPATH: ${{ github.workspace }}/swag_Automation_QA/robotframework/robot_lib

    steps:
      - name: 清理工作區
        run: |
          rm -rf swag_Automation_QA/results/
          rm -rf swag_Automation_QA/reports/

      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 執行測試
        id: test
        continue-on-error: true
        run: |
          cd swag_Automation_QA
          mkdir -p results
          arch -arm64 robot \
            -v BROWSER:chrome \
            -v SELENIUM_TIMEOUT:60 \
            -v SELENIUM_IMPLICIT_WAIT:30 \
            -V data.yaml \
            -V country.yaml \
            -V ${ENVIRONMENT}_domain.yaml \
            -i ${TEST_TYPE} \
            --outputdir results \
            TestCase

      - name: 分析測試結果
        id: analyze_results
        run: |
          python3 <<EOF
          import os
          from xml.etree import ElementTree as ET

          result_file = 'swag_Automation_QA/results/output.xml'
          pass_count = fail_count = 0

          if os.path.exists(result_file):
              tree = ET.parse(result_file)
              root = tree.getroot()
              for suite in root.iter('suite'):
                  for test in suite.iter('test'):
                      if test.attrib['status'] == 'PASS':
                          pass_count += 1
                      elif test.attrib['status'] == 'FAIL':
                          fail_count += 1

          print(f"測試完成！\n通過測試數: {pass_count}\n失敗測試數: {fail_count}")

          if fail_count > 0:
              exit(1)
          EOF

      - name: 打印測試結果
        if: success()
        run: echo "所有測試均通過！"

      - name: 打印失敗結果
        if: failure()
        run: echo "部分測試失敗，請檢查測試結果！"

      - name: 上傳測試結果
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.TEST_TYPE }}
          path: |
            swag_Automation_QA/results/
          if-no-files-found: warn